version: '3.9'

services: 
  redis:
    image: redis:7.0.4-alpine
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - '6379:6389'